apiVersion: v1
kind: Service
metadata:
  name: pullreq-tracker
spec:
  selector:
    app: pullreq-tracker
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pullreq-tracker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pullreq-tracker
  template:
    metadata:
      labels:
        app: pullreq-tracker
    spec:
      containers:
        - name: pullreq-tracker
          image: 840684697633.dkr.ecr.us-east-1.amazonaws.com/dev-iq_pullreq-tracker:latest
          ports:
            - containerPort: 8083
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
