apiVersion: batch/v1
kind: CronJob
metadata:
  name: init-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: init-cronjob
              image: 840684697633.dkr.ecr.us-east-1.amazonaws.com/dev-iq_init-job:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_secret_access_key
          restartPolicy: OnFailure
          activeDeadlineSeconds: 600
