apiVersion: v1
kind: Service
metadata:
  name: init
spec:
  selector:
    app: init
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-deployment
spec:
  selector:
    matchLabels:
      app: init
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
        - name: init
          image: 840684697633.dkr.ecr.us-east-1.amazonaws.com/dev-iq_init:latest
          ports:
            - containerPort: 8084
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: init-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: init-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
