apiVersion: v1
kind: Service
metadata:
  name: commit-tracker
spec:
  selector:
    app: commit-tracker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: commit-tracker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commit-tracker
  template:
    metadata:
      labels:
        app: commit-tracker
    spec:
      containers:
        - name: commit-tracker
          image: 840684697633.dkr.ecr.us-east-1.amazonaws.com/dev-iq_init
          ports:
            - containerPort: 8081
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
